import { PrismaClient } from '@prisma/client'

const db = new PrismaClient()

const SECTORS = [
  'Software Development & Engineering',
  'Artificial Intelligence & Machine Learning',
  'FinTech & Digital Payments',
  'Cybersecurity & InfoSec',
  'HealthTech & Telemedicine',
  'EdTech & E-Learning',
  'AgriTech & Smart Farming',
  'E-Commerce & Digital Marketplace',
  'Cloud Computing & DevOps',
  'IoT & Embedded Systems',
  'Robotics & Industrial Automation',
  'Renewable Energy & CleanTech',
  'Blockchain & Web3',
  'Game Development & Esports',
  'AR / VR & Spatial Computing',
  'Logistics & Supply Chain Tech',
  'PropTech & Real Estate Tech',
  'Aerospace & Defense Technology',
  'Semiconductor & VLSI Design',
  'Data Analytics & Business Intelligence',
  'Digital Marketing & AdTech',
  'Automotive & Electric Vehicles (EV)',
  'InsurTech & Risk Management',
  'Media, Film & Creative Tech',
  'HRTech & Talent Management',
  'BioTech & Genomics',
  'Nanotechnology & Materials Science',
  'GovTech & Smart Cities',
  'LegalTech & Regulatory Tech',
  'Telecommunications & 5G',
  'TravelTech & Hospitality',
  'FoodTech & QSR Tech',
  'Social Networking & Community',
  'Hardware Design & Prototyping',
  'Computer Vision & Image Processing',
  'Generative AI & LLM Applications',
  'IT Consulting & Enterprise Solutions',
  'SaaS & B2B Platforms',
  'FashionTech & Wearables',
  'Fintech / Software / SaaS',
  'Software Development / IT Services',
  'Marketing / Advertising / Software',
  'Social Networking / Online Platform',
  'Renewable Energy / Energy Solutions',
  'AI / Software / Fashion Tech',
  'Digital Product Design / Development',
  'Remote Hiring / Software Services',
  'AI Recruitment / Enterprise IT / Cybersecurity',
  'Film / Photography / Media',
  'Web / Mobile / Digital Marketing',
  'Web / Mobile / AI / Computer Vision',
  'Engineering / Manufacturing / R&D',
  'Multiple Industries',
  'Marketing / E-commerce',
  'AI / Automation / Mobility / Embedded Systems',
  'Software / Design / AI / Digital Agency',
  'Digital Products / Software / Consulting',
  'Event Planning / Services Marketplace',
  'Web / App Development / Digital Solutions',
  'AI / Business Analytics / Chatbots',
  'Web Development / Digital Marketing / Software Solutions',
  'STEAM Education / EdTech',
  'AI / Content Creation / Mobile Apps',
  'Image Processing / Machine Learning / Embedded Systems',
  'Software House / Web & App Development / E-Commerce',
  'Co-working Spaces / Business Services',
  'AI / Machine Learning / Automation',
  'AI / Product Development / Strategy',
  'Music / Media / Production',
  'Generative AI / Web & Mobile Development',
  'Tourism / Travel / Content Creation',
]

const PAKISTAN_CITIES = [
  // Federal Capital
  'Islamabad',
  
  // Punjab
  'Lahore',
  'Rawalpindi',
  'Faisalabad',
  'Multan',
  'Gujranwala',
  'Sialkot',
  'Gujrat',
  'Bahawalpur',
  'Sargodha',
  'Sahiwal',
  'Sheikhupura',
  'Rahim Yar Khan',
  'Jhelum',
  'Kasur',
  'Attock',
  'Chakwal',
  'Okara',
  'Khanewal',
  'Vehari',
  'Muzaffargarh',
  'Mandi Bahauddin',
  'Hafizabad',
  'Toba Tek Singh',
  'Dera Ghazi Khan',
  'Layyah',
  'Bhakkar',
  'Mianwali',
  'Khushab',
  'Pakpattan',
  'Lodhran',
  'Rajanpur',
  'Chiniot',
  'Nankana Sahib',
  'Taxila',
  'Wah Cantt',
  'Murree',
  'Bhalwal',
  'Burewala',
  'Chishtian',
  'Daska',
  'Gojra',
  'Jaranwala',
  'Kamoke',
  'Kot Addu',
  'Pattoki',
  'Sadiqabad',
  'Sambrial',
  'Samundri',
  'Shorkot',
  'Wazirabad',

  // Sindh
  'Karachi',
  'Hyderabad',
  'Sukkur',
  'Larkana',
  'Nawabshah (Shaheed Benazirabad)',
  'Mirpur Khas',
  'Jacobabad',
  'Shikarpur',
  'Khairpur',
  'Dadu',
  'Thatta',
  'Badin',
  'Ghotki',
  'Jamshoro',
  'Umerkot',
  'Tando Allahyar',
  'Tando Muhammad Khan',
  'Matiari',
  'Kashmore',
  'Sanghar',
  'Kandhkot',
  'Kotri',
  'Shahdadkot',
  'Tando Adam',

  // Khyber Pakhtunkhwa (KP)
  'Peshawar',
  'Abbottabad',
  'Mardan',
  'Mingora (Swat)',
  'Haripur',
  'Mansehra',
  'Nowshera',
  'Charsadda',
  'Kohat',
  'Dera Ismail Khan',
  'Bannu',
  'Swabi',
  'Malakand',
  'Timergara (Dir)',
  'Chitral',
  'Hangu',
  'Karak',
  'Tank',
  'Batkhela',
  'Risalpur',
  'Topi',
  'Parachinar',

  // Balochistan
  'Quetta',
  'Gwadar',
  'Turbat',
  'Khuzdar',
  'Hub',
  'Chaman',
  'Sibi',
  'Zhob',
  'Loralai',
  'Jaffarabad',
  'Nasirabad',
  'Kalat',
  'Dera Murad Jamali',
  'Pishin',
  'Usta Muhammad',
  'Nushki',
  'Kharan',

  // Azad Jammu & Kashmir (AJK)
  'Muzaffarabad',
  'Mirpur (AJK)',
  'Rawalakot',
  'Kotli',
  'Bhimber',
  'Bagh',
  'Pallandri',
  'Hattian Bala',
  'Haveli',

  // Gilgit-Baltistan (GB)
  'Gilgit',
  'Skardu',
  'Hunza',
  'Diamer (Chilas)',
  'Ghizer',
  'Ghanche',
  'Astore',
  'Nagar',
  'Shigar',
  'Kharmang',

  // Common International Hubs for Pakistani / SEECS Diaspora
  'San Francisco (USA)',
  'New York (USA)',
  'Seattle (USA)',
  'Austin (USA)',
  'London (UK)',
  'Manchester (UK)',
  'Dubai (UAE)',
  'Abu Dhabi (UAE)',
  'Riyadh (Saudi Arabia)',
  'Jeddah (Saudi Arabia)',
  'Doha (Qatar)',
  'Berlin (Germany)',
  'Munich (Germany)',
  'Amsterdam (Netherlands)',
  'Dublin (Ireland)',
  'Stockholm (Sweden)',
  'Toronto (Canada)',
  'Vancouver (Canada)',
  'Sydney (Australia)',
  'Melbourne (Australia)',
  'Singapore',
  'Tokyo (Japan)',
  'Kuala Lumpur (Malaysia)',
]

async function run() {
  console.log('Bulk seeding Sectors and Cities...')

  // Distinct arrays
  const uniqueSectors = Array.from(new Set(SECTORS.map(s => s.trim())))
  const uniqueCities = Array.from(new Set(PAKISTAN_CITIES.map(c => c.trim())))

  const sectorRes = await db.sector.createMany({
    data: uniqueSectors.map(name => ({ name })),
    skipDuplicates: true,
  })

  const cityRes = await db.city.createMany({
    data: uniqueCities.map(name => ({ name })),
    skipDuplicates: true,
  })

  const [totalSectors, totalCities] = await Promise.all([
    db.sector.count(),
    db.city.count(),
  ])

  console.log(`✅ Success! Inserted ${sectorRes.count} sectors (Total: ${totalSectors}), Inserted ${cityRes.count} cities (Total: ${totalCities})`)
}

run()
  .catch(console.error)
  .finally(() => db.$disconnect())
