INSERT INTO founder (name, gender, degree_id) VALUES
    ('Jawad Haider', 'Male', 1),
    ('Usman Ishaq', 'Male', 2),
    ('Abdul Basit', 'Male', 3),
    ('Usama Tauqeer', 'Male', 4),
    ('Umair Javaid', 'Male', 5),
    ('Faizan Zahid', 'Male', 6),
    ('Farooq Saeed', 'Male', 7),
    ('Awais Shafique', 'Male', 8),
    ('Hamza Shahid', 'Male', 9),
    ('Annus Shahid', 'Male', 10),
    ('Sohaib Ishtiaq', 'Male', 11),
    ('Ameer Hamza Baig', 'Male', 12),
    ('Faraz Mirza', 'Male', 13),
    ('Muhammad Ali', 'Male', 14),
    ('Asif Ahmed Ali', 'Male', 15),
    ('Ali Farooq', 'Male', 16),
    ('Momin Munir', 'Male', 17),
    ('Afnan Sharief', 'Male', 18),
    ('Waseem Khan', 'Male', 19),
    ('Ahsan Tahir', 'Male', 20),
    ('Daniyal Yasin', 'Male', 21),
    ('Aadil Jaleel Choudhry', 'Male', 22),
    ('Yousaf Iqbal', 'Male', 23),
    ('Junaid Khattak', 'Male', 24),
    ('Muhammad Shehroz Sajjad', 'Male', 25),
    ('Syed Muhammad Tayyab', 'Male', 26),
    ('Izzah Zaman', 'Female', 27),
    ('Neelam Shoaib', 'Female', 28),
    ('Muhammad Kamran Akbar', 'Male', 29),
    ('Farah Tahir', 'Female', 30),
    ('Ramsha Khuram', 'Female', 31),
    ('Faisal Zahid', 'Male', 32),
    ('Faisal Laghari', 'Male', 33),
    ('Muhammad Abdullah Rafique', 'Male', 34),
    ('Zain ul Abedien', 'Male', 35),
    ('Abuzar Faris', 'Male', 36),
    ('Abdul Moeed Khalid', 'Male', 37),
    ('Junaid Naeem', 'Male', 38),
    ('Muhammad Mohsin', 'Male', 39),
    ('Ameed Khalid', 'Male', 40),
    ('Syed Muneeb Ali', 'Male', 41),
    ('Talha Irfan', 'Male', 42),
    ('Uridah Sami Ahmed', 'Female', 43),
    ('Hassan Jalil', 'Male', 44),
    ('Iqra Irfan', 'Female', 45),
    ('Waqas Ahmed', 'Male', 46),
    ('Ehmad Zubair', 'Male', 47),
    ('Abdul Hanan', 'Male', 48),
    ('Kashif Manzoor', 'Male', 49);
