INSERT INTO sector (name) VALUES 
    ('Fintech / Software / SaaS'),
    ('Software Development / IT Services'),
    ('Marketing / Advertising / Software'),
    ('Social Networking / Online Platform'),
    ('Renewable Energy / Energy Solutions'),
    ('AI / Software / Fashion Tech'),
    ('Digital Product Design / Development'),
    ('Remote Hiring / Software Services'),
    ('AI Recruitment / Enterprise IT / Cybersecurity'),
    ('Film / Photography / Media'),
    ('Web / Mobile / Digital Marketing'),
    ('Web / Mobile / AI / Computer Vision'),
    ('Engineering / Manufacturing / R&D'),
    ('Multiple Industries'),
    ('Marketing / E-commerce'),
    ('AI / Automation / Mobility / Embedded Systems'),
    ('Software / Design / AI / Digital Agency'),
    ('Digital Products / Software / Consulting'),
    ('Event Planning / Services Marketplace'),
    ('Web / App Development / Digital Solutions'),
    ('AI / Business Analytics / Chatbots'),
    ('Web Development / Digital Marketing / Software Solutions'),
    ('STEAM Education / EdTech'),
    ('AI / Content Creation / Mobile Apps'),
    ('Image Processing / Machine Learning / Embedded Systems'),
    ('Software House / Web & App Development / E-Commerce'),
    ('Co-working Spaces / Business Services'),
    ('AI / Machine Learning / Automation'),
    ('AI / Product Development / Strategy'),
    ('Music / Media / Production'),
    ('Generative AI / Web & Mobile Development'),
    ('Tourism / Travel / Content Creation');